### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by schulzch** [garyharan/jQuery-caret-utilities#4]
First off: your plugin is awesome. As there is no license referenced, it'll open legal issues for its users. If you don't care much about legal stuff, I'd suggest the MIT license (=use it and leave me alone):

> Licensed under the incredibly permissive MIT License. Copyright © 2013 <Name>.

Regards,
Christoph

**Comment by garyharan** [comment]
Great idea!

https://github.com/garyharan/jQuery-caret-utilities/commit/f129daf18840fa4737c6e22fcceaa3cddfc896bb

I can't believe I didn't think of adding the licence! :-D

**Comment by schulzch** [comment]
Thanks :-)
